# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70ca13c36811786c0538eac386374093906acc55547d8c47e9ad80b8505618e118276b05929490347b59e7e8bd3ab65f9493fe14f21dc34688d6e774ec78f9a3

test:
  secret_key_base: 893f37b7cb884f0bd4a6c08230b21425abb5556ead298f57374a6bf302fbd70799cb78a33dcfab5c22b797c3d2f1048ae5b312d330cae39383e302dc2b0dad8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
